# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4db5d0a6ed0c14143e7c9052c99a9a4ac548e565ae3de1daf03098896fa8c729f143a3fd6f9dd357e19b85b75740891a9d90325c5c18128eb36f222f1efad12

test:
  secret_key_base: 8ca0f4abd8a33197593dc5472b8d1b1bfb35d8342f1aa8d7316b990d6aa471daf7e7823df77e432d19b2205a682ca84a9a2c5c784a6212974a2ea8859df6ac56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
